// ══════════════════════════════════════════════════════
// summary.js · Summary page (EN site) — thumbnail overview of every panel
//
// Data: data/summary_thumbs.json (generated by scripts/build_summary.py, refreshed daily)
// Each card = panel title + mini chart; click → index.html#panel-xxx
// Mini charts use ECharts (loaded from CDN), stripped of axis labels/legend/tooltip,
// instantiated only when they scroll into view (55 charts → lazy render).
// ══════════════════════════════════════════════════════

const DATA_URL = 'data/summary_thumbs.json?v=20261007152848';
const PALETTE = ['#2563eb', '#389e0d', '#cf1322', '#d48806', '#722ed1'];

const grid = document.getElementById('summaryGrid');
let charts = [];

document.querySelectorAll('.nav-summary, .category-summary').forEach(el => el.classList.add('active'));
document.querySelectorAll('.category-tab').forEach(el => el.classList.remove('active'));

function miniOption(rec) {
  const series = (rec.series || []).filter(s => (s.pts && s.pts.length) || (s.xy && s.xy.length));
  const base = {
    animation: false,
    grid: { left: 4, right: 4, top: 6, bottom: 6, containLabel: false },
    tooltip: { show: false },
    legend: { show: false },
    xAxis: { type: 'category', show: false, boundaryGap: rec.kind === 'bar' },
    yAxis: { type: 'value', show: false, scale: true },
  };
  if (rec.kind === 'scatter') {
    return {
      ...base,
      xAxis: { type: 'value', show: false, scale: true },
      yAxis: { type: 'value', show: false, scale: true },
      series: series.map(s => ({
        type: 'scatter', data: s.xy, symbolSize: 3, color: PALETTE[0], silent: true,
      })),
    };
  }
  return {
    ...base,
    series: series.map((s, i) => {
      const color = s.name ? PALETTE[i % PALETTE.length] : PALETTE[0];
      const data = (s.labels || []).map((l, j) => [l, s.pts[j]]);
      return {
        type: rec.kind === 'bar' ? 'bar' : 'line',
        data: s.labels ? data : s.pts,
        color,
        silent: true,
        symbol: 'none',
        smooth: false,
        lineStyle: { width: 1.6 },
        areaStyle: rec.kind === 'area' ? { opacity: 0.14 } : undefined,
        barMaxWidth: 14,
      };
    }),
  };
}

function decoSvg(d) {
  const W = 220, H = 44;
  let inner = '';
  const t = d && d.type;
  if (t === 'yearstrip') {
    const n = Math.max(Math.min(d.n || 40, 90), 2);
    for (let i = 0; i < n; i++) {
      const x = 4 + i * ((W - 8) / (n - 1));
      const h = 10 + ((i * 37) % 22);
      inner += `<line x1="${x.toFixed(1)}" y1="${(H / 2 - h / 2).toFixed(1)}" x2="${x.toFixed(1)}" y2="${(H / 2 + h / 2).toFixed(1)}" stroke="currentColor" stroke-width="1.2" stroke-linecap="round" opacity="${(0.3 + (i % 5) * 0.14).toFixed(2)}"/>`;
    }
  } else if (t === 'squares') {
    const n = Math.max(Math.min(d.n || 7, 9), 1);
    const s = 12;
    const gap = (W - 40 - n * s) / Math.max(n - 1, 1);
    for (let i = 0; i < n; i++) {
      const x = 20 + i * (s + gap);
      inner += `<rect x="${x.toFixed(1)}" y="${(H / 2 - s / 2).toFixed(1)}" width="${s}" height="${s}" rx="2" fill="${i % 2 === 0 ? 'currentColor' : 'none'}" stroke="currentColor" stroke-width="1.2" opacity="${i % 2 === 0 ? 0.5 : 0.28}"/>`;
    }
  } else if (t === 'lines') {
    const n = Math.max(Math.min(d.n || 4, 6), 1);
    for (let i = 0; i < n; i++) {
      const y = 10 + i * ((H - 20) / Math.max(n - 1, 1));
      const w = W - 40 - i * 22;
      inner += `<rect x="20" y="${y.toFixed(1)}" width="${w.toFixed(0)}" height="4" rx="2" fill="currentColor" opacity="${(0.45 - i * 0.06).toFixed(2)}"/>`;
    }
  } else if (t === 'quote') {
    inner = `<text x="${W / 2}" y="${H / 2 + 2}" text-anchor="middle" dominant-baseline="middle" font-size="32" fill="currentColor" opacity="0.42">“”</text>`;
  }
  return `<svg viewBox="0 0 ${W} ${H}" class="summary-deco" aria-hidden="true">${inner}</svg>`;
}

function renderCard(rec) {
  const a = document.createElement('a');
  a.className = 'summary-card';
  a.href = `index.html#${rec.id}`;

  const head = document.createElement('div');
  head.className = 'summary-card-head';
  head.textContent = rec.en || rec.id;
  a.appendChild(head);

  const thumb = document.createElement('div');
  thumb.className = 'summary-thumb';
  a.appendChild(thumb);

  if (rec.kind === 'none' || !(rec.series || []).length) {
    thumb.classList.add('is-text');
    const icon = document.createElement('div');
    icon.className = 'summary-thumb-icon';
    icon.innerHTML = rec.deco
      ? decoSvg(rec.deco)
      : '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><path d="M5 5h14M5 10h14M5 15h9" stroke-linecap="round"/></svg>';
    const txt = document.createElement('span');
    txt.textContent = rec.preview || 'Charts';
    thumb.appendChild(icon);
    thumb.appendChild(txt);
  } else {
    charts.push({ el: thumb, rec });
  }
  return a;
}

function build(data) {
  grid.innerHTML = '';
  const byCat = {};
  data.panels.forEach(p => { (byCat[p.cat] = byCat[p.cat] || []).push(p); });

  data.categories.forEach(cat => {
    const list = byCat[cat.id] || [];
    if (!list.length) return;
    const sec = document.createElement('section');
    sec.className = 'summary-section';
    sec.dataset.category = cat.id;
    const h = document.createElement('h2');
    h.className = 'summary-cat-head';
    h.innerHTML = `${cat.en}<span class="summary-cat-count">${list.length}</span>`;
    sec.appendChild(h);
    const g = document.createElement('div');
    g.className = 'summary-grid';
    list.forEach(p => g.appendChild(renderCard(p)));
    sec.appendChild(g);
    grid.appendChild(sec);
  });

  const io = new IntersectionObserver((entries, obs) => {
    entries.forEach(e => {
      if (!e.isIntersecting) return;
      obs.unobserve(e.target);
      const item = charts.find(c => c.el === e.target);
      if (item) {
        try {
          const chart = echarts.init(item.el, null, { renderer: 'svg' });
          chart.setOption(miniOption(item.rec));
        } catch (err) { console.warn('[summary] chart failed', item.rec.id, err); }
      }
    });
  }, { rootMargin: '200px' });
  charts.forEach(c => io.observe(c.el));

  const tabs = Array.from(document.querySelectorAll('.category-tab[data-category]'));
  tabs.forEach(tab => tab.addEventListener('click', () => {
    tabs.forEach(t => t.classList.toggle('active', t === tab));
    const target = tab.dataset.category;
    document.querySelectorAll('.summary-section').forEach(s => {
      s.hidden = s.dataset.category !== target;
    });
    window.scrollTo({ top: 0, behavior: 'auto' });
  }));
}

fetch(DATA_URL, { cache: 'no-store' })
  .then(r => { if (!r.ok) throw new Error('HTTP ' + r.status); return r.json(); })
  .then(build)
  .catch(err => {
    console.warn('[summary] load failed', err);
    grid.innerHTML = '<div class="summary-loading">Failed to load summary data. Please retry later.</div>';
  });
