// ══════════════════════════════════════════════════════
// summary.js · Summary page (EN site)
//
// Data: data/summary_thumbs.json (generated by scripts/build_summary.py, refreshed daily)
// Layout: **one continuous horizontal grid** — all cards flow left→right and wrap
//         (same structure as the debt-board summary page); category info lives in a
//         small chip on each card plus the top tabs used as filters.
// Click a card → index.html#panel-xxx; click a category tab → filter; click Summary → show all.
// Mini charts use ECharts (loaded from CDN), stripped of axes/legend/tooltip, lazily created.
// ══════════════════════════════════════════════════════

const DATA_URL = 'data/summary_thumbs.json?v=20261008001527';
const PALETTE = ['#2563eb', '#389e0d', '#cf1322', '#d48806', '#722ed1'];

/* Per-category theme colours (set by 老钱 on 2026-10-07):
   Nasdaq 100 & Dow (cross) → green #389e0d; Fund Flows (flows) → red #cf1322.
   Other categories keep the PALETTE default (single series = blue). Only colours already
   defined in theme.css are used; multi-series cards in a themed category vary by opacity. */
const CAT_THEME = { cross: '#389e0d', flows: '#cf1322' };
const hexA = (hex, a) => `rgba(${(parseInt(hex.slice(1), 16) >> 16) & 255},${(parseInt(hex.slice(1), 16) >> 8) & 255},${parseInt(hex.slice(1), 16) & 255},${a})`;
function seriesColor(rec, s, i) {
  const theme = CAT_THEME[rec.cat];
  if (!theme) return s.name ? PALETTE[i % PALETTE.length] : PALETTE[0];
  if (!s.name || i === 0) return theme;
  return hexA(theme, i === 1 ? 0.5 : 0.28);
}

const grid = document.getElementById('summaryGrid');
let charts = [];
let catLabel = {};

document.querySelectorAll('.nav-summary, .category-summary').forEach(el => el.classList.add('active'));
document.querySelectorAll('.category-tab').forEach(el => el.classList.remove('active'));

function miniOption(rec) {
  const series = (rec.series || []).filter(s => (s.pts && s.pts.length) || (s.xy && s.xy.length));
  const base = {
    animation: false,
    grid: { left: 4, right: 4, top: 6, bottom: 6, containLabel: false },
    tooltip: { show: false },
    legend: { show: false },
    xAxis: { type: 'category', show: false, boundaryGap: rec.kind === 'bar' },
    yAxis: { type: 'value', show: false, scale: true },
  };
  if (rec.kind === 'scatter') {
    return {
      ...base,
      xAxis: { type: 'value', show: false, scale: true },
      yAxis: { type: 'value', show: false, scale: true },
      series: series.map(s => ({
        type: 'scatter', data: s.xy, symbolSize: 3, color: CAT_THEME[rec.cat] || PALETTE[0], silent: true,
      })),
    };
  }
  return {
    ...base,
    series: series.map((s, i) => {
      const color = seriesColor(rec, s, i);
      const data = (s.labels || []).map((l, j) => [l, s.pts[j]]);
      return {
        type: rec.kind === 'bar' ? 'bar' : 'line',
        data: s.labels ? data : s.pts,
        color,
        silent: true,
        symbol: 'none',
        smooth: false,
        lineStyle: { width: 1.6 },
        areaStyle: rec.kind === 'area' ? { opacity: 0.14 } : undefined,
        barMaxWidth: 14,
      };
    }),
  };
}

function decoSvg(d) {
  const W = 220, H = 44;
  let inner = '';
  const t = d && d.type;
  if (t === 'yearstrip') {
    const n = Math.max(Math.min(d.n || 40, 90), 2);
    for (let i = 0; i < n; i++) {
      const x = 4 + i * ((W - 8) / (n - 1));
      const h = 10 + ((i * 37) % 22);
      inner += `<line x1="${x.toFixed(1)}" y1="${(H / 2 - h / 2).toFixed(1)}" x2="${x.toFixed(1)}" y2="${(H / 2 + h / 2).toFixed(1)}" stroke="currentColor" stroke-width="1.2" stroke-linecap="round" opacity="${(0.3 + (i % 5) * 0.14).toFixed(2)}"/>`;
    }
  } else if (t === 'squares') {
    const n = Math.max(Math.min(d.n || 7, 9), 1);
    const s = 12;
    const gap = (W - 40 - n * s) / Math.max(n - 1, 1);
    for (let i = 0; i < n; i++) {
      const x = 20 + i * (s + gap);
      inner += `<rect x="${x.toFixed(1)}" y="${(H / 2 - s / 2).toFixed(1)}" width="${s}" height="${s}" rx="2" fill="${i % 2 === 0 ? 'currentColor' : 'none'}" stroke="currentColor" stroke-width="1.2" opacity="${i % 2 === 0 ? 0.5 : 0.28}"/>`;
    }
  } else if (t === 'lines') {
    const n = Math.max(Math.min(d.n || 4, 6), 1);
    for (let i = 0; i < n; i++) {
      const y = 10 + i * ((H - 20) / Math.max(n - 1, 1));
      const w = W - 40 - i * 22;
      inner += `<rect x="20" y="${y.toFixed(1)}" width="${w.toFixed(0)}" height="4" rx="2" fill="currentColor" opacity="${(0.45 - i * 0.06).toFixed(2)}"/>`;
    }
  } else if (t === 'quote') {
    inner = `<text x="${W / 2}" y="${H / 2 + 2}" text-anchor="middle" dominant-baseline="middle" font-size="32" fill="currentColor" opacity="0.42">“”</text>`;
  }
  return `<svg viewBox="0 0 ${W} ${H}" class="summary-deco" aria-hidden="true">${inner}</svg>`;
}

function renderCard(rec) {
  const a = document.createElement('a');
  a.className = 'summary-card';
  a.href = `index.html#${rec.id}`;
  a.dataset.cat = rec.cat || '';

  const head = document.createElement('div');
  head.className = 'summary-card-head';
  const t = document.createElement('span');
  t.className = 'summary-card-title';
  t.textContent = rec.en || rec.id;
  head.appendChild(t);
  if (catLabel[rec.cat]) {
    const chip = document.createElement('span');
    chip.className = 'summary-chip';
    chip.textContent = catLabel[rec.cat];
    head.appendChild(chip);
  }
  a.appendChild(head);

  const thumb = document.createElement('div');
  thumb.className = 'summary-thumb';
  a.appendChild(thumb);

  if (rec.kind === 'none' || !(rec.series || []).length) {
    thumb.classList.add('is-text');
    const icon = document.createElement('div');
    icon.className = 'summary-thumb-icon';
    icon.innerHTML = rec.deco
      ? decoSvg(rec.deco)
      : '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><path d="M5 5h14M5 10h14M5 15h9" stroke-linecap="round"/></svg>';
    const txt = document.createElement('span');
    txt.textContent = rec.preview || 'Charts';
    thumb.appendChild(icon);
    thumb.appendChild(txt);
  } else {
    charts.push({ el: thumb, rec });
  }
  return a;
}

function applyFilter(cat) {
  document.querySelectorAll('.summary-card').forEach(c => {
    c.hidden = !!cat && c.dataset.cat !== cat;
  });
  const tabs = Array.from(document.querySelectorAll('.category-tab[data-category]'));
  tabs.forEach(t => t.classList.toggle('active', !!cat && t.dataset.category === cat));
  document.querySelectorAll('.category-summary').forEach(el => el.classList.toggle('active', !cat));
  window.scrollTo({ top: 0, behavior: 'auto' });
}

function build(data) {
  grid.innerHTML = '';
  charts = [];
  catLabel = {};
  data.categories.forEach(c => { catLabel[c.id] = c.en; });

  const g = document.createElement('div');
  g.className = 'summary-grid';
  data.panels.forEach(p => g.appendChild(renderCard(p)));
  grid.appendChild(g);

  const io = new IntersectionObserver((entries, obs) => {
    entries.forEach(e => {
      if (!e.isIntersecting) return;
      obs.unobserve(e.target);
      const item = charts.find(c => c.el === e.target);
      if (item) {
        try {
          const chart = echarts.init(item.el, null, { renderer: 'svg' });
          chart.setOption(miniOption(item.rec));
        } catch (err) { console.warn('[summary] chart failed', item.rec.id, err); }
      }
    });
  }, { rootMargin: '200px' });
  charts.forEach(c => io.observe(c.el));

  document.querySelectorAll('.category-tab[data-category]').forEach(tab => {
    tab.addEventListener('click', () => applyFilter(tab.dataset.category));
  });
  document.querySelectorAll('.category-summary').forEach(el => {
    el.addEventListener('click', (ev) => { ev.preventDefault(); applyFilter(null); });
  });
}

fetch(DATA_URL, { cache: 'no-store' })
  .then(r => { if (!r.ok) throw new Error('HTTP ' + r.status); return r.json(); })
  .then(build)
  .catch(err => {
    console.warn('[summary] load failed', err);
    grid.innerHTML = '<div class="summary-loading">Failed to load summary data. Please retry later.</div>';
  });
